name: Run All Mocha Tests

on:
  push:
    branches:
      - master

jobs:
  mocha-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true
      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: 16.x
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-test-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-test-
      - name: Install dependencies
        run: yarn install
      - name: Create .env file
        run: |
          jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' <<< "$SECRETS_CONTEXT" > .env
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
      - name: Run All Tests
        run: yarn test -- --timeout 9999
        env:
          NODE_ENV: test
